### ISSUE TITLE
[possible bug?] MacOS not able to login

### ISSUE THREAD

**Issue by paulo-roger** [rystaf/mlmym#63] opened 2023-07-31 14:20 UTC
I  think it is worth investigating.

I have had users from 2 different instances reporting they are not able to login from MacOS.

Here is a video and a Console screenshot:

![screenshot-console_error](https://github.com/rystaf/mlmym/assets/103009333/07c164a4-c951-4c3f-bbe1-b75ca91f4641)
[video](https://i.imgur.com/nNmXy93.mp4)

**Comment by rystaf** [comment] 2023-07-31 19:11
Works for me on MacOS. And I'm not seeing that Content Security Policy error. Maybe have them try clearing site cache/cookies?

![Screen Recording 2023-07-31 at 3 04 40 PM](https://github.com/rystaf/mlmym/assets/2389047/ce12f8d3-b351-4c83-ba57-ca24ee75596f)

**Comment by paulo-roger** [comment] 2023-07-31 20:38
I have asked them to clear the cache and the problem persists. Maybe could it be a 2FA error then?

**Comment by rystaf** [comment] 2023-07-31 21:14
Possibly. Have them try clicking the login link at the top right and login there. Instead of using the form under the search field. It might give a more helpful error message.

**Comment by BeyondCombustion** [comment] 2023-08-11 00:15
@rystaf I'm on macOS and can login, wasn't able to prior to fixing a 2fa issue and updating to lemmy 0.18.4 + mlmym 0.25.


 I didn't try again for like 2 weeks after I opened a separate bug report, thinking it was the 2fa (would get 400 or 401 depending on password/2fa combo tried) or extra / in the URL. Today I did turn 2fa on and back off, then decided to give old.instance.com a try and everything works no problem now.

Since getting mlmym working earlier, I just updated it to the latest versions and can confirm I am able to login (without having 2factor enabled at least) on macOS with the following versions installed:

[lemmy / lemmy-ui docker](https://hub.docker.com/layers/dessalines/lemmy/0.18.4/images/sha256-09279a3617722c6c33b9f20a2d9d6f4d5f6b57551463d771b7c25062d75f465f): 0.18.4 running rootless
and 
[mlmym](https://github.com/rystaf/mlmym): 0.0.27 also running rootless, on a separate VM.

**Comment by JakeShirley** [comment] 2023-08-15 15:51
When I couldn't log into the my instance with mlmyn I looked at the dev console and it was because I hadn't set up https for mlmyn so it couldn't store any secure cookies.

**Comment by Crul** [comment] 2023-11-01 18:56
> I hadn't set up https for mlmyn so it couldn't store any secure cookies.

@JakeShirley May I ask how do you set up https for mlmym?
I'm a noob regarding docker. I've been able to run the mlmym docker image and it works... until I try to log in. Not sure if the problem is HTTPS because I have a Commafeed instance working on HTTP and it seems it has no problem with cookies... but it's worth a try.

Thanks!

**Comment by rystaf** [comment] 2024-07-09 14:25
This may have been caused by a bug fixed in 0.0.46 that prevented logging in with email address instead of username. If this is still happening to anyone, please let us know with any details you can provide.

**Closed by rystaf** 2024-07-09 14:25 UTC
